-- Create timeline table
CREATE TABLE IF NOT EXISTS public.timeline (
    id int4 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    title varchar NOT NULL,
    description text NOT NULL,
    time varchar NOT NULL,
    created_at timestamp NULL DEFAULT now(),
    updated_at timestamp NULL DEFAULT now(),
    CONSTRAINT timeline_pkey PRIMARY KEY (id)
);

-- Add comment to the table
COMMENT ON TABLE public.timeline IS 'Timeline events table';

-- Add comments to columns
COMMENT ON COLUMN public.timeline.id IS 'Primary key for timeline events';
COMMENT ON COLUMN public.timeline.title IS 'Title of the timeline event';
COMMENT ON COLUMN public.timeline.description IS 'Description of the timeline event';
COMMENT ON COLUMN public.timeline.time IS 'Time/date of the timeline event (e.g., "May, 2020")';
COMMENT ON COLUMN public.timeline.created_at IS 'Timestamp when the event was created';
COMMENT ON COLUMN public.timeline.updated_at IS 'Timestamp when the event was last updated';

-- Insert initial data
INSERT INTO public.timeline (title, description, time) VALUES
    ('Vercel was founded in SF, USA', 'Vercel Inc., formerly ZEIT, is an American cloud platform as a service company. The company maintains the Next.js web development framework.', 'May, 2020'),
    ('Shadcn First Commit', 'Beautifully designed components that you can copy and paste into your apps. Accessible. Customizable. Open Source.', 'January, 2023'),
    ('Shadcn Timeline', 'Shadcn timeline component. Open Source.', 'November, 2024'); 