name: Dev Integration
on:
  workflow_dispatch:
  push:
    branches:
      - dev

jobs:
  integration:
    name: Continuous Integration
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "^22"

      # Install dependencies
      - name: Install dependencies
        run: npm install

      # Run linting to check code quality
      - name: Run lint
        run: npm run lint

      # Check if the app builds successfully
      - name: Build the app
        run: npm run build
        env:
          NEXT_PUBLIC_SUPABASE_URL: ${{ secrets.NEXT_PUBLIC_SUPABASE_URL }}
          NEXT_PUBLIC_SUPABASE_ANON_KEY: ${{ secrets.NEXT_PUBLIC_SUPABASE_ANON_KEY }}
